name: CI Checks

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  merge_group:

env:
  CI: true

jobs:
  qa-test:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'do not build') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Cache test results
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .vitest
          key: vitest-${{ runner.os }}-${{ hashFiles('**/*.test.ts') }}
          restore-keys: |
            vitest-${{ runner.os }}-

      - name: Run Biome CI checks
        run: pnpm biome ci --reporter=github --reporter=default --changed --since=origin/${{ github.base_ref }}
